[package]
name = "condenser"
type = "bin"
authors = ["Willem Olding <willemolding@gmail.com>"]

[dependencies]
bignum = { tag = "v0.8.3", git = "https://github.com/noir-lang/noir-bignum" }
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
keccak256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/keccak256" }
