[package]
name = "transfer-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
light-concurrent-merkle-tree = "5.0.0"
light-hasher = "5.0.0"
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
light-bounded-vec = "2.0.1"

[dev-dependencies]
num-bigint = "0.4.6"

