[package]
name = "transfer-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
light-sparse-merkle-tree = "0.3.0"
light-hasher = "5.0.0"
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
light-poseidon = "0.4.0"

[dev-dependencies]
num-bigint = "0.4.6"

